version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha_root_aqui
      MYSQL_DATABASE: seu_banco_de_dados_aqui
    volumes:
      - /home/BancoMysql:/var/lib/mysql
    ports:
      - "3306:3306"
