version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bola@2020
      MYSQL_DATABASE: db_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
